# バージョン2記法で記述する
version: '2'

# 起動するコンテナを定義する
services:

    # Play Frameworkコンテナ
    play:
        # DockerfileによってPlay Frameworkイメージの自作を目指す
        # このファイルと同じフォルダーのDockerfileを使う
        build: ./

        # コンテナ名を指定する
        # Docker Composeが自動生成するコンテナ名は長く、タイピングが面倒なため
        container_name: play

        volumes:
          - ./src:/root/src

    # MySQLのコンテナ
    mysql:
        platform: linux/x86_64 # M1チップ対応のため追記
        image: mysql:5.6
        ports:
          - 3307:3306
        restart: on-failure
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=scraping
          - MYSQL_USER=root
          - MYSQL_PASSWORD=password
        volumes:
          - ./mysql:/var/lib/mysql
        container_name: mysql_db